#!/bin/bash
export TESTING=0
export SRC="/usr/local/bin/pomodoro-timer"
export SRC="."
ADDONS_PRE_BREAK="$SRC/pre_break.sh"	# Add To File as needed
ADDONS_POST_BREAK="$SRC/post_break.sh" # Add To File as needed

# Export Environment Variables
$SRC/setup_env.sh

# Kill
echo "To stop the timer, do 'screen -r'"
echo "Then hit ctrl-c"

#pomodoro 
screen -dm bash -c "pomodoro_timer $ADDONS_PRE_BREAK $ADDONS_POST_BREAK; exec bash"
